services:
  - type: web
    name: hng-ticket-app
    runtime: docker
    repo: https://github.com/Kimathii/HNG-TICKET-APP-C
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true